version: appveyor.{build}

platform:
  - x64

os:
 - Visual Studio 2019
 
configuration:
  - Release
  - Debug

branches:
  only:
  - master
  - develop

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 1
  AVTTS_VERBOSE: 1
  QTDIR: 'C:\Qt\5.12.4\msvc2015_64'
  PATH: '%QTDIR%\bin;%PATH%'

init:
  - cmd: git config --global core.autocrlf true

  # System related variables
  - cmd: set CMAKE_GENERATOR=Visual Studio
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set CMAKE_GENERATOR=%CMAKE_GENERATOR% 16 2019
  - cmd: if "%Platform%"=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - cmd: echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

   # Prepare AVTTS for tests
  - cmd: set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\build\bin\%CONFIGURATION%
  
  # Print some useful informations:
  - cmd: set
  - cmd: cmake --version
  - cmd: msbuild /version

before_build:
  - cmd: cmake -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%\build -G"%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%\install

build:
  project: build\avtts.sln
  parallel: false
  verbosity: minimal

#after_build:
 # - cmd: cmake --build %APPVEYOR_BUILD_FOLDER%\build --target PACKAGE --config %CONFIGURATION%
 # - cmd: move /Y %APPVEYOR_BUILD_FOLDER%\build\*.exe %APPVEYOR_BUILD_FOLDER%

#test_script:
  #- cmd: cmake --build %APPVEYOR_BUILD_FOLDER%\build --target RUN_TESTS --config %CONFIGURATION%

